# Name of the GitHub Actions workflow
name: Deploy when develop branch is merged into the main branch.

# Trigger the workflow on push and pull request events to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  # Define a job named "ci"
  ci:
    # Specify the operating system to run the job on
    runs-on: ubuntu-latest
    
    # Define the steps to be executed in the job
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: 21.x

      # Install dependencies
      - name: 🧰 Install Dependencies
        run: npm install

      # Install Cypress binary
      - name: Install Cypress
        run: npx cypress install

      # Run Lint and Tests
      - name: Run Tests
        run: |
          npm run lint
          npm run test
          npm run test-component

      # Deploy step: Only run if this is the main branch
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        # Set the deployment URL from secrets
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$DEPLOY_URL"
