# Name of workflow
name: Test workflow when a Pull Request is made from stanleybranch to the develop branch.

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop
      - stanleybranch

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2  # Update to v2 for more stability and performance

      # Set up Node.js
      - name: Use Node.js 21.x
        uses: actions/setup-node@v2  # Update to v2 for more stability and performance
        with:
          node-version: 21.x

      # Install dependencies
      - name: 🧰 Install Deps
        run: |
          cd server && npm install && cd ../client && npm install

      # Install Cypress binary
      - name: Install Cypress
        run: npx cypress install

      # Run lint
      - name: Run Lint
        run: npm run lint

      # Run build
      - name: Run Build
        run: npm run build

      # Run tests
      - name: Run Tests
        run: npm run test
